name: PlatformIO CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Install dependencies
      run: |
        pio platform install espressif32 --with-package framework-arduinoespressif32 --with-package tool-esptoolpy
        pio lib -e all-deps install --no-save
        mv .pio/libdeps/all-deps/* lib/
    - name: Copy secrets
      run: cp include/secrets.example.h include/secrets.h
    - name: Build demo
      run: pio run -e demo
    - name: Build spectrum
      run: pio run -e spectrum
    - name: Build m5plusdemo
      run: pio run -e m5plusdemo
    - name: Build heltecdemo
      run: pio run -e heltecdemo
    - name: Build xmastrees
      run: pio run -e xmastrees
    - name: Build brooklynroom
      run: pio run -e brooklynroom
    - name: Build ledstrip
      run: pio run -e ledstrip
    - name: Build panlee
      run: pio run -e panlee
